AllCops:
  TargetRubyVersion: 2.6.5
  Include:
    -  'app/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails:
  Enabled: true